/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_five_onair_server_utils_FileUtils */

#ifndef _Included_com_five_onair_server_utils_FileUtils
#define _Included_com_five_onair_server_utils_FileUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_five_onair_server_utils_FileUtils
 * Method:    copyDirectoryLikeRoot
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_five_onair_server_utils_FileUtils_copyDirectoryLikeRoot
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
